### ISSUE TITLE
Remember last selected electorate and redirect there when landing on home page late

### ISSUE THREAD

**Issue by robinst** [robinst/ausballot#1]
From https://www.reddit.com/r/AustralianPolitics/comments/umwy7g/comment/i8aknc1/?utm_source=share&utm_medium=web2x&context=3:

> Persist the filled in ballot papers as a landing page. (When I return to the website I have to select the electorate again when this is unnecessary if previously chosen)

We can save the last selected electorate in local storage. The tricky bit might be recognizing if the user is going to the home page by clicking the navigation (in that case we do *not* want to go back to the electorate), vs the user coming to the landing page through a fresh page load.

**Comment by naiknareshh** [comment]
Hi Robin, I have created a PR that fixes this issue with the following approach - 
1. Save Electorate in local storage whenever user selects an Electorate from the Home page.
2. Whenever the user comes back to the landing page, application checks if there is data in local storage and redirects to Ballot.
3. When user clicks 'Home' navigation button then the local storage is cleared and user will not be redirected to the Ballot.

I am assuming there should be a functionality to store 'Division' and 'Senate' values also, let me know if this needs to be added as well
